#constants for test. Also has dictionaries for mapping constants back to names


DEVICE_ID_BUTTON_A =  1                       
DEVICE_ID_BUTTON_B = 2
DEVICE_ID_BUTTON_AB = 3
DEVICE_ID_BUTTON_RESET= 4
DEVICE_ID_ACCELEROMETER = 5
DEVICE_ID_COMPASS = 6
DEVICE_ID_DISPLAY = 7
DEVICE_ID_THERMOMETER = 8
DEVICE_ID_RADIO = 9
DEVICE_ID_RADIO_DATA_READY = 10
DEVICE_ID_MULTIBUTTON_ATTACH = 11
DEVICE_ID_SERIAL = 12
DEVICE_ID_GESTURE = 13
DEVICE_ID_SYSTEM_TIMER = 14
DEVICE_ID_SCHEDULER = 15
DEVICE_ID_COMPONENT = 16
DEVICE_ID_LIGHT_SENSOR = 17
DEVICE_ID_TOUCH_SENSOR = 18
DEVICE_ID_SYSTEM_DAC = 19
DEVICE_ID_SYSTEM_MICROPHONE = 20
DEVICE_ID_SYSTEM_LEVEL_DETECTOR = 21
DEVICE_ID_SYSTEM_LEVEL_DETECTOR_SPL = 22
DEVICE_ID_MSC = 23
DEVICE_ID_SPI = 24

DEVICE_ID_DISTANCE = 25
DEVICE_ID_GYROSCOPE = 26
DEVICE_ID_HUMIDITY = 27
DEVICE_ID_PRESSURE = 28

DEVICE_ID_SINGLE_WIRE_SERIAL =29
DEVICE_ID_JACDAC = 30
DEVICE_ID_JACDAC_PHYS = 31
DEVICE_ID_JACDAC_CONTROL_SERVICE = 32
DEVICE_ID_JACDAC_CONFIGURATION_SERVICE = 33
DEVICE_ID_SYSTEM_ADC = 34
DEVICE_ID_PULSE_IN = 35
DEVICE_ID_USB = 36

DEVICE_ID_IO_P0 = 100


DEVICE_BUTTON_EVT_DOWN = 1
DEVICE_BUTTON_EVT_UP = 2
DEVICE_BUTTON_EVT_CLICK = 3
DEVICE_BUTTON_EVT_LONG_CLICK = 4
DEVICE_BUTTON_EVT_HOLD = 5
DEVICE_BUTTON_EVT_DOUBLE_CLICK = 6

ACCELEROMETER_EVT_NONE = 0
ACCELEROMETER_EVT_TILT_UP = 1
ACCELEROMETER_EVT_TILT_DOWN = 2
ACCELEROMETER_EVT_TILT_LEFT = 3
ACCELEROMETER_EVT_TILT_RIGHT = 4
ACCELEROMETER_EVT_FACE_UP = 5 
ACCELEROMETER_EVT_FACE_DOWN = 6
ACCELEROMETER_EVT_FREEFALL = 7
ACCELEROMETER_EVT_3G = 8 
ACCELEROMETER_EVT_6G = 9
ACCELEROMETER_EVT_8G = 10
ACCELEROMETER_EVT_SHAKE = 11
ACCELEROMETER_EVT_2G = 12

ACCELEROMETER_EVT_DATA_UPDATE = 1


COMPASS_EVT_DATA_UPDATE = 1
COMPASS_EVT_CONFIG_NEEDED = 2
COMPASS_EVT_CALIBRATE = 3
COMPASS_EVT_CALIBRATION_NEEDED = 4

MICROBIT_THERMOMETER_EVT_UPDATE = 1

RADIO_EVT_DATA_READY = 2

CODAL_SERIAL_EVT_DELIM_MATCH = 1
CODAL_SERIAL_EVT_HEAD_MATCH = 2
CODAL_SERIAL_EVT_RX_FULL = 3
CODAL_SERIAL_EVT_DATA_RECEIVED = 4

COMPONENTS_NAME_DICT = {1 : 'DEVICE_ID_BUTTON_A',                       
2: 'DEVICE_ID_BUTTON_B',
3: 'DEVICE_ID_BUTTON_AB' ,
4:'DEVICE_ID_BUTTON_RESET',
5:'DEVICE_ID_ACCELEROMETER',
6: 'DEVICE_ID_COMPASS',
7: 'DEVICE_ID_DISPLAY',
8: 'DEVICE_ID_THERMOMETER',
9: 'DEVICE_ID_RADIO',
10: 'DEVICE_ID_RADIO_DATA_READY',
11: 'DEVICE_ID_MULTIBUTTON_ATTACH',
12:'DEVICE_ID_SERIAL',
13:'DEVICE_ID_GESTURE',
14:'DEVICE_ID_SYSTEM_TIMER',
15:'DEVICE_ID_SCHEDULER' ,
16:'DEVICE_ID_COMPONENT',
17:'DEVICE_ID_LIGHT_SENSOR' ,
18:'DEVICE_ID_TOUCH_SENSOR',
19:'DEVICE_ID_SYSTEM_DAC' ,
20:'DEVICE_ID_SYSTEM_MICROPHONE',
21:'DEVICE_ID_SYSTEM_LEVEL_DETECTOR' ,
22:'DEVICE_ID_SYSTEM_LEVEL_DETECTOR_SPL' ,
23:'DEVICE_ID_MSC',
24:'DEVICE_ID_SPI' ,
25:'DEVICE_ID_DISTANCE' ,
26:'DEVICE_ID_GYROSCOPE',
27:'DEVICE_ID_HUMIDITY' ,
28:'DEVICE_ID_PRESSURE' ,
29:'DEVICE_ID_SINGLE_WIRE_SERIAL' ,
30:'DEVICE_ID_JACDAC' ,
31:'DEVICE_ID_JACDAC_PHYS' ,
32:'DEVICE_ID_JACDAC_CONTROL_SERVICE',
33:'DEVICE_ID_JACDAC_CONFIGURATION_SERVICE',
34:'DEVICE_ID_SYSTEM_ADC' ,
35:'DEVICE_ID_PULSE_IN' ,
36:'DEVICE_ID_USB' ,
100:'DEVICE_ID_IO_P0'}


GESTURE_EVENTS_DICT = {0: "ACCELEROMETER_EVT_NONE",
1: "ACCELEROMETER_EVT_TILT_UP",
2: 'ACCELEROMETER_EVT_TILT_DOWN',
3:'ACCELEROMETER_EVT_TILT_LEFT',
4:'ACCELEROMETER_EVT_TILT_RIGHT',
5:'ACCELEROMETER_EVT_FACE_UP',
6:'ACCELEROMETER_EVT_FACE_DOWN',
7:'ACCELEROMETER_EVT_FREEFALL',
8:'ACCELEROMETER_EVT_3G',
9:'ACCELEROMETER_EVT_6G',
10:'ACCELEROMETER_EVT_8G',
11:'ACCELEROMETER_EVT_SHAKE',
12:'ACCELEROMETER_EVT_2G'
}

BUTTON_EVENTS_DICT ={1:'DEVICE_BUTTON_EVT_DOWN',
2:'DEVICE_BUTTON_EVT_UP',
3:'DEVICE_BUTTON_EVT_CLICK',
4:'DEVICE_BUTTON_EVT_LONG_CLICK',
5:'DEVICE_BUTTON_EVT_HOLD',
6:'DEVICE_BUTTON_EVT_DOUBLE_CLICK'
}

ACCEL_EVENTS_DICT = {1:"ACCELEROMETER_EVT_DATA_UPDATE"}

COMPASS_EVENTS_DICT = {1: "COMPASS_EVT_DATA_UPDATE",
2: "COMPASS_EVT_CONFIG_NEEDED",
3: "COMPASS_EVT_CALIBRATE",
4: "COMPASS_EVT_CALIBRATION_NEEDED"}

THERMOMETER_EVENTS_DICT = {1:"MICROBIT_THERMOMETER_EVT_UPDATE"}

RADIO_EVENTS_DICT = {2: 'RADIO_EVT_DATA_READY'}

SERIAL_EVENTS_DICT = {1:'CODAL_SERIAL_EVT_DELIM_MATCH',
2:'CODAL_SERIAL_EVT_HEAD_MATCH',
3:'CODAL_SERIAL_EVT_RX_FULL',
4:'CODAL_SERIAL_EVT_DATA_RECEIVED'}


EVENTS_DICT = {1: BUTTON_EVENTS_DICT,
2: BUTTON_EVENTS_DICT,
3: BUTTON_EVENTS_DICT,
4: BUTTON_EVENTS_DICT,
5: ACCEL_EVENTS_DICT,
6: COMPASS_EVENTS_DICT,
7: None,
8: THERMOMETER_EVENTS_DICT,
9:  RADIO_EVENTS_DICT,
12: SERIAL_EVENTS_DICT,
13: GESTURE_EVENTS_DICT}
